import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/auth/AuthContext";
import { ActiveTimeEntryProvider } from "@/activeTimeEntry/ActiveTimeEntryContext";
import { ThemeProvider  } from "@/theme/ThemeProvider";
import ThemeToggle from "@/components/ThemeToggle";
import { ProjectsProvider } from "@/project/ProjectContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <ProjectsProvider>
              <ActiveTimeEntryProvider>
                {children}
              </ActiveTimeEntryProvider>
            </ProjectsProvider>
          </AuthProvider>
          <div className="fixed bottom-4 right-4">
            <ThemeToggle/>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
